name: snyk scan

on:
  workflow_call:
    inputs:
      # valid options: python, dotnet, golang, nodejs
      language-tooling:
        description: "Programming language or building tool used"
        required: false
        type: string
        default: dotnet

    secrets:
      snyk_api_token:
        description: Snyk API Token
        required: true

jobs:
  snyk-scan:
    name: snyk scan
    runs-on: ubuntu-20.04

    defaults:
      run:
        shell: bash

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Run Snyk scan for .Net
        if: ${{ inputs.language-tooling == 'dotnet'}}
        uses: snyk/actions/dotnet@master
        env:
          SNYK_TOKEN: ${{ secrets.snyk_api_token }}
        with:
          command: monitor

      - name: Run Snyk scan for python
        if: ${{ inputs.language-tooling == 'python'}}
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.snyk_api_token }}
        with:
          command: monitor

      - name: Run Snyk scan for golang
        if: ${{ inputs.language-tooling == 'golang'}}
        uses: snyk/actions/golang@master
        env:
          SNYK_TOKEN: ${{ secrets.snyk_api_token }}
        with:
          command: monitor

      - name: Run Snyk scan for nodeJS
        if: ${{ inputs.language-tooling == 'nodejs'}}
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.snyk_token }}
        with:
          command: monitor
