name: Base NodeJS Pipeline

on: 
  workflow_dispatch:


jobs:

  snyk-nodejs-scan:
    name: NodeJS code scan
    uses: filipefigueredo/nestjs-hello-ts/.github/workflows/snyk-code-scan.workflow.yaml@master
    with:
      language-tooling: nodejs
    secrets:
      snyk_api_token: ${{ secrets.SNYK_API_TOKEN }}

  snyk-docker-scan:
    name: Container image scan
    uses: filipefigueredo/nestjs-hello-ts/.github/workflows/snyk-code-scan.workflow.yaml@master
    with:
      language-tooling: docker
      image_tag: latest
    secrets:
      snyk_api_token: ${{ secrets.SNYK_API_TOKEN }}

  nodejs-build:
    name: NodeJS build and test
    uses: filipefigueredo/nestjs-hello-ts/.github/workflows/nodejs-build.workflow.yaml@master
    with:
      node-version: '16'
      
  docker-image:
    name: docker image
    uses: filipefigueredo/nestjs-hello-ts/.github/workflows/docker.workflow.yaml@master

  new-image:
    needs: docker-image
    name: new image
    uses: filipefigueredo/nestjs-hello-ts/.github/workflows/docker.workflow.yaml@master
    with:
      image_tag: '1.0.0'

