name: base random nodejs pipeline

on:
  workflow_dispatch:

jobs:
  snyk-nodejs-scan:
    name: nodejs code scan
    uses: filipefigueredo/nestjs-hello-ts/.github/workflows/snyk-scan.workflow.yaml@master
    with:
      language-tooling: nodejs
    secrets:
      snyk_api_token: ${{ secrets.SNYK_API_TOKEN }}

  snyk-docker-scan:
    name: container image scan
    uses: filipefigueredo/nestjs-hello-ts/.github/workflows/snyk-scan.workflow.yaml@master
    with:
      language-tooling: docker
      image_tag: latest
    secrets:
      snyk_api_token: ${{ secrets.SNYK_API_TOKEN }}

  nodejs-build:
    name: nodejs build and test
    uses: filipefigueredo/nestjs-hello-ts/.github/workflows/nodejs-build.workflow.yaml@master
    with:
      node-version: '16'

  versioned-container-image:
    name: build versioned container image
    uses: filipefigueredo/nestjs-hello-ts/.github/workflows/docker.workflow.yaml@master
    with:
      image_tag: '1.0.0'

  latest-container-image:
    name: build latest container image
    needs: versioned-container-image:
    uses: filipefigueredo/nestjs-hello-ts/.github/workflows/docker.workflow.yaml@master
