name: container image build and publish

on:
  workflow_call:
    inputs:
      container_image_tag:
        description: 'Container image tag'
        required: false
        type: string
        default: latest

jobs:
  ## Build container image and publish it to container registry
  build-container-image:
    name: build and publish container image
    runs-on: ubuntu-20.04

    env:
      CONTAINER_REGISTRY_NAME: 'ghcr.io'

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up / Install Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.CONTAINER_REGISTRY_NAME }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      # Parse and lower case image name
      - name: Parse container image name
        id: lowercase
        run: |
          parsed_string=$(echo "${{ env.CONTAINER_REGISTRY_NAME }}/${{github.repository_owner}}/${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          echo "$parsed_string"
          echo "::set-output name=container_image_name::$parsed_string"
      - name: echo
        run: echo "${{ env.CONTAINER_REGISTRY_NAME }}/${{github.repository_owner}}/A" | tr '[:upper:]' '[:lower:]'
      - name: aye aye
        run: echo "${{ steps.lowercase.container_image_name }}"

      # Build and push the container image to container registry
      # Note: this step uses GitHub Cache AOI to fetch and upload container image layers
      - name: Build and push container image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.lowercase.container_image_name }}:${{ inputs.container_image_tag }}
          cache-from: type=gha
          cache-to: type=gha
