name: container image build

on:
  workflow_call:
    inputs:
      image_tag:
        description: 'Container image tag'
        required: false
        type: string
        default: latest
      target-directory:
        description: "Target working directory"
        required: false
        type: string
        default: "."

jobs:
  ## Build container image and publish it
  build-container-image:
    name: Build container image
    runs-on: ubuntu-20.04

    env:
      REGISTRY_NAME: 'ghcr.io'
      IMAGE_NAME: ${{ github.repository }}

    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.target-directory }}

    permissions:
      packages: write

    steps:
      - name: Checkout repository codebase
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_NAME }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push container image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ inputs.image_tag }}
          cache-from: type=gha
          cache-to: type=gha
