on:
  workflow_call:
    inputs:
      image_tag:
        description: 'Container image tag'
        required: false
        type: string
        default: latest
    secrets:
      registry_name:
        description: Container registry name
        required: true
      registry_username:
        description: Container registry username
        required: true
      registry_password:
        description: Password or personal access token used to log against the container registry
        required: true

jobs:
  ## Build container image and publish it
  build-container-image:
    name: Build container image
    runs-on: ubuntu-20.04

    permissions:
      packages: write

    env:
      REGISTRY_NAME: 'ghcr.io'
      IMAGE_NAME: ${{ github.repository }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository codebase
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_NAME }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push container image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ inputs.image_tag }}
          cache-from: type=gha
          cache-to: type=gha
