on:
  workflow_call:
    inputs:
      # valid options: python, dotnet, golang, nodejs
      organization_name:
        description: Container registry organization name
        required: false
        default: ${{ github.event.organization.name }}
      image_name:
        description: 'Container image name'
        required: false
        type: string
        default: ${{ github.event.repository.name }}
      image_tag:
        description: 'Container image tag'
        required: true
        type: string
        default: latest
    secrets:
      registry_name:
        description: Container registry hostname
        required: false
        default: hub.docker.io
      registry_username:
        description: Container registry username
        required: false
      registry_password:
        description: Password or personal access token used to log against the container registry
        required: true

  
jobs:
  ## Build container image and publish it
  build-container-image:
    name: Build container image
    runs-on: ubuntu-20.04
    env: 
      IMAGE_NAME: ${{ github.event.organization.name }}/${{ github.event.repository.name }}

    steps:
      - name: Checkout repository codebase
        uses: actions/checkout@v3

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.registry_hostname }}
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}

      - name: Build and push container image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.registry_name }}/${{ inputs.organization_name }}/${{ inputs.repository_name }}:${{ inputs.image_tag }}
            
